- name: add_to_log
  type: AddToLog
- name: brake_release
  type: Trigger
- name: clear_operational_mode
  type: Trigger
- name: close_popup
  type: Trigger
- name: close_safety_popup
  type: Trigger
- name: connect
  type: Trigger
- name: get_loaded_program
  type: GetLoadedProgram
- name: get_robot_mode
  type: GetRobotMode
- name: get_safety_mode
  type: GetSafetyMode
- name: load_installation
  type: Load
- name: load_program
  type: Load
- name: pause
  type: Trigger
- name: play
  type: Trigger
- name: popup
  type: Popup
- name: power_off
  type: Trigger
- name: power_on
  type: Trigger
- name: program_running
  type: IsProgramRunning
- name: program_saved
  type: IsProgramSaved
- name: program_state
  type: GetProgramState
- name: quit
  type: GetLoadedProgram
- name: raw_request
  type: RawRequest
- name: restart_safety
  type: Trigger
- name: shutdown
  type: Trigger
- name: stop
  type: Trigger
- name: unlock_protective_stop
  type: Trigger
