left_drt_ur_gui:
  ros__parameters:
    dashboard_client_name: "left_dashboard_client"
    freedrive_mode_controller_name: "left_"
    robot.name: "UR"
    arm.name: "Left Arm"
    program: "ext_ctrl.urp"
    logo_file_name: 'iMETRO_full.png'
    window.name: "DRT UR Remote Commander: Dual Arm Testing Configuration"
    window.stylesheet: |
      QMainWindow{
        background-color: #7d94f7;
        color: #000000;
      }
      QPlainTextEdit{
        background-color: #a5adcf;
        color: #000000;
      }
      QTableWidget{
        background-color: #a5adcf;
      }
      QTableWidget QHeaderView::section {
        background-color: #a5adcf;
      }
      QTreeWidget{
        background-color: #a5adcf;
      }
      QTreeWidget QHeaderView::section {
        background-color: #a5adcf;
      }
      QPushButton{
        background-color: #3f60f3;
      }
      QComboBox{
       background-color: #e7ebfd;
      }
      QComboBox QAbstractItemView{
        background-color: #e7ebfd;
      }
      QComboBox QAbstractItemView::item:selected {
        background-color: #e7ebfd;
      }
