right_drt_ur_gui:
  ros__parameters:
    dashboard_client_name: "right_dashboard_client"
    robot.name: "UR"
    arm.name: "Right Arm"
    program: "ext_ctrl.urp"
    logo_file_name: 'iMETRO_full.png'
    window.name: "DRT UR Remote Commander: Dual Arm Testing Configuration"
    window.stylesheet: |
      QMainWindow{
        background-color: #f7937d;
        color: #000000;
      }
      QPlainTextEdit{
        background-color: #cfada5;
        color: #000000;
      }
      QTableWidget{
        background-color: #cfada5;
      }
      QTableWidget QHeaderView::section {
        background-color: #cfada5;
      }
      QTreeWidget{
        background-color: #cfada5;
      }
      QTreeWidget QHeaderView::section {
        background-color: #cfada5;
      }
      QPushButton{
        background-color: #f3603f;
      }
      QComboBox{
       background-color: #fdebe7;
      }
      QComboBox QAbstractItemView{
        background-color: #fdebe7;
      }
      QComboBox QAbstractItemView::item:selected {
        background-color: #fdebe7;
      }
