#!/usr/bin/env python3
#
# Copyright (c) 2025, United States Government, as represented by the
# Administrator of the National Aeronautics and Space Administration.
#
# All rights reserved.
#
# This software is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""Fixes incompatible object names in .ui files generated by Qt Creator

Arguments:
    filename (str): Path to .ui file, required positional argument

Creating a backup of your UI file before running this is recommended. \n
Fixes are applied by recursively searching the XML tree of the provided .ui file for class names containing multiple
scope resolution operators (::). Results are not guaranteed.

Qt Creator applies fully qualified object names to .ui files that the ROS 2 Qt5 binding package fails to understand.

Running this script on a .ui file saved from Qt Creator attempts to make the file compatible with ROS 2
python_qt_bindings by removing the scope specifiers from any object names that have them.
I.e. "Qt::Orientation::Vertical" becomes "Qt::Vertical"

Compatibility issues with python_qt_bindings can be avoided in general by only using the most simple widgets and widget
properties. Favor using basic widgets like frames, layouts, and splitters in favor of setting widget properties to
achieve the UI look you want.
"""

import argparse
import xml.etree.ElementTree as ET


def main(filename: str):
    tree = ET.parse(filename)
    root = tree.getroot()
    fix_tree(root)
    tree.write(filename, encoding="utf-8", xml_declaration=True)
    return


def fix_tree(etree):
    for child in etree:
        if len(child) > 0:
            fix_tree(child)
        else:
            if child.text is not None and child.text.count("::") > 1:
                print(f"Problem attribute found: {child.text}")
                attribute_parts = child.text.split("::")
                child.text = "::".join([attribute_parts[0], attribute_parts[-1]])
                print(f"Problem attribute altered to {child.text}")
    return


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__,  # reuses the docstring at the top of the file
        # formatter_class preserves the format of the file's docstring when printed with --help
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("filename", help="Path to the ui file you would like to fix")
    args = parser.parse_args()
    main(args.filename)
